name: build_check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.18.2"
      - name: Install Dependencies
        run: npm install
      - name: check-build
        run: npm run build
